if psf_getmodlocale() == "zhTW" then
    function rsclocalel()

        rscdefaultzone1 = "納克薩瑪斯"        
        rscdefaultzone2 = "亞夏梵穹殿"

        psfpotchecklocal = "藥水檢查"
        psfpotchecklocalt2 = "精煉合劑檢查"
        psfpotchecklocalt3 = "復活 - 重新BUFF"
		psfpotchecklocalt322 = "戰鬥中復活後的增益狀態檢查"
		
        rscbuffnameslit1 = "王者祝福"
        rscbuffnameslit2 = "野性賜福"
        rscbuffnameslit3 = "耐力"
        rscbuffnameslit4 = "精神"
        rscbuffnameslit5 = "暗影防護"
        rscbuffnameslit6 = "智力"
        rscbuffnameslit7 = "智慧祝福"
        rscbuffnameslit8 = "力量祝福"
        rscbuffnameslit9 = "奧術光輝"
        rscbuffspart1 = "這個模塊會檢查妳所選擇的增益"
        rscbuffspart2 =
            "戰復以後報告丟失了哪些增益，然後再復查他們"
        rscbuttonreset = "重置"
        rscchatlist1 = "團隊"
        rscchatlist2 = "團隊警告"
        rscchatlist3 = "幹部"
        rscchatlist4 = "隊伍"
        rscchatlist5 = "公會"
        rscchatlist6 = "說"
        rscchatlist7 = "大喊"
        rscchatlist8 = "自己"
        rscflasktext10 = "全部已有精煉合劑和食物的buff"
        rscflasktext11 = "所有人都有精煉合劑"
        rscflasktext12 = "無數據.有許多死亡/斷線"
        rscflasktext2 = "自動檢查發佈的頻道"
        rscflasktext3 = "先檢查"
        rscflasktext4 = "只有一個藥劑效果"
        rscflasktext5 = "無精煉合劑"
        rscflasktext6 = "沒有人擁有"
        rscflasktext7 = "無食物buff"
        rscflasktext8 = "只食物buff"
        rscflasktext9 = "未檢查"
        rscflasktextc11 =
			"在boss倒計時開戰的時候公佈（只支持ICC）"
		rscflasktextc12 = "在倒計時開始的時候公告"
        rscflasktextc13 = "在發起團隊准備確認的時候公告"
        rscflasktextc14 = "自動檢查時發送密語"
        rscflasktextc15 = "檢查食物"
        rscflasktxtgroup2 = "組"
        rscflasktxtgroup5 = "組"
        rscflaskwhisptxt1 = "PhoenixStyle > 妳沒有食物增益！"
        rscflaskwhisptxt2 = "PhoenixStyle > 妳只擁有一個藥劑效果"
        rscflaskwhisptxt3 = "PhoenixStyle > 妳沒有精煉合劑或者藥劑！"
        rscflaskwhisptxt4 =
            "PhoenixStyle > 妳沒有食物增益併且只有一個藥劑效果"
        rscflaskwhisptxt5 = "PhoenixStyle > 妳沒有精煉合劑和食物效果"
        rsclocallpot = "全部藥水"
        rscloccolor = "職業上色"
        rsclocfight1 = "最近一次戰鬥" 
        rsclocfight2 = "前次戰鬥"
        rsclocfight3 = "戰鬥"
        rscloclastf = "最後戰鬥"
        rsclocnotinc = "戰鬥外"
        rsclocpot10 = "誰使用藥水"
        rsclocpot11 = "誰沒使用藥水"
        rsclocpot12 = "前次戰鬥的藥水"
        rsclocpot13 = "前次戰鬥所使用的藥水"
        rsclocpot14 = "前次戰鬥前未使用之藥水"
        rsclocpot15 = "針對前次戰鬥之前使用過的藥水"
        rsclocpot16 = "前次戰鬥前未使用藥水:"
        rsclocpot17 = "沒有人使用藥水"
        rsclocpot18 = "使用過的藥水"
        rsclocpot2 = "未選擇藥水"
        rsclocpot3 = "沒使用藥水"
        rsclocpot4 = "每個人都有使用藥水"
        rsclocpot5 = "資訊關於"
        rsclocpot6 = "無藥水:"
        rsclocpot7 = "沒有檢測到精煉合劑"
        rsclocpot8 = "其他使用的藥水"
        rsclocpot9 = "沒有其他使用的藥水"
        rsclocrep1 = "發佈到頻道裏"
        rsclocrlslak = "發佈RL精煉合劑"
        rscpartanons31 = "當1被選擇的時候在聊天窗口公告"
        rscpartanons32 = "當2被選擇的時候在聊天窗口公告"
        rscpartanons33 = "當1選擇的時候發送密語"
		rscpartanons34 = "當2選擇的時候發送密語"
		rscpartanons35 = "沒有助理權限也發送公告"
        rscpartanons36 = "如果使用了藥劑，要求同時使用兩種"
		rscparton3 = "開啟"
        -- rscpartwhobuff1 = ""
        rscreleasedtxt1 = "被戰複了"
        rscreleasedtxt1f = "已復活"
        rscreleasedtxt2 = "前"
        rscreleasedtxt3 = "沒有補上"
        rscreleasedtxt4 = "還是沒有補上"
        rscreleasedtxt5 = "第二次檢查"
        rscreleasedtxt6 = "但是還是沒有被補上"
        rscreleasedtxt6f = "但是還是沒有被補上"
        rscreleasedtxt7 = "但是沒有補上"
        rscreleasedtxt7f = "但是沒有補上"
        rscreloadbutton = "更新"
		rscsec = "秒"
		rscflasktext1 = "除了常規的精煉合劑和食物檢查外，此模塊還具有獨特的選項，可以在boss戰鬥開始、准備檢查或使用PhoenixStyle插件的倒計時（Pull-timer）時自動檢查和報告偷懶的玩家（50秒內最多檢查1次，戰鬥開始時的檢查除外）。"		
		rscflasktext1part2 = "低於|cffff0000%s|r分鐘剩余持續時間Buff視為無效。"		
		rscaddonnotworkinz = "模塊在部分指定區域不會激活:"
		rscsend = "更新和發送"
		
		rscbuttonztext1 = "添加當前區域"
		rscbuttonztext2 = "刪除當前區域"
		rscbuttonztext3 = "顯示區域列錶"
		rscbuttonztext4 = "重置區域列錶"
		rsclocrlslak = "檢查團長"
		rscbuffspart3 =
        "您可以為增益效果設置負責人（例如：如果您的團隊中沒有聖騎士 - 輸入使用戰鼓的人的名字），然後如果他們在團隊中還活著，第一次檢查時只會私聊他們，否則會私聊所有可以施放增益的玩家。"
    
		rscpartwhobuff1 = "BUFF的負責人:"
    end

end